[tool.poetry]
name = "faker_module"
version = "0.1.0"
description = ""
authors = ["Ptran32"]

[tool.poetry.dependencies]
python = "^3.7"
Faker = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
